### ISSUE TITLE
missing hid.framework.

### ISSUE THREAD

**Issue by johndpope** [shiroholloway/HID-Explorer#1]
keen to look at your implementation on nssplitviewcontroller. apple's resources are scarce.

**Comment by arsdraconis** [comment]
Hi John,

This project depends on my [HIDKit project](https://github.com/shiroholloway/HIDKit) to work. I'm not good at git submodules so I didn't include it, but you should be able to throw both of them together into an Xcode workspace then build and run.

I can tell you up front, however, that my split view controller is nothing special. All I added was a method to toggle the collapsed state of the source list in the sidebar. That said, I wish I had known the following three things when I first started messing with an NSSplitViewController...
1. When you drag one in from the palette in Interface Builder, the NSSplitView's delegate outlet is not hooked up. You need to manually set its delegate to your NSSplitViewController for it to behave correctly.
2. To allow a split view item to collapse, make sure you mark the "Can Collapse" checkbox for that item in Interface Builder. If you want that item to maintain a minimum size before collapsing, give that item's view controller a width/height constraint greater than or equal to your desired minimum size. Assuming the NSSplitView's delegate is hooked up to NSSplitViewController, it will then work automagically.
3. Set the holding priority on your content split view item to less than that of any sidebar split view items. That way the split view mimics Apple's own apps, where the content area in a window grows/shrinks as the window size is changed while source lists and inspectors remain a constant width.

Let me know if you run into any more trouble.

**Comment by johndpope** [comment]
ok thx. I didn't realise that it only got introduced in 10.10. I'm going to have to park it and fall back on nssplitview.  Thx for your feedback
